gme_options_mart:
  target: "{{ env_var('DBT_TARGET', 'dev') }}"
  outputs:
    dev:
      type: duckdb
      path: "target/gme_options.duckdb"
      schema: main
      threads: 1
      extensions:
        - httpfs
        - json

    motherduck:
      type: duckdb
      path: "{{ env_var('GME_MOTHERDUCK_PATH', 'md:gme_options') }}"
      schema: main
      threads: 1
      extensions:
        - httpfs
        - json
