"""
{mart_name} Dashboard — Streamlit Presentation Layer

Generated by mart-forge scaffold from the signed BRD/TDD contract.
Metrics and link statuses are bound to the signed design document.
Sections: mode banner, DQC scorecard, metric cards, trend chart, provenance.
Connects to DuckDB (local fixture or MotherDuck-compatible URI via env).
"""

import json
import os
from pathlib import Path

import duckdb
import streamlit as st

MART_NAME = "{mart_name}"
DB_PATH = os.getenv("MART_DB_PATH", "{db_name}.duckdb")
DQC_SCORECARD_PATH = os.getenv("DQC_SCORECARD_PATH", "dqc_scorecard.json")
IS_FIXTURE_MODE = os.getenv("MART_FIXTURE_MODE", "true").lower() == "true"

ADS_TABLE = "{prefix}_ads_exec_dashboard"
DWS_TABLE = "{prefix}_dws_daily_revenue_1d"

CONTRACTED_METRICS = {contract_metrics}

LINK_STATUS_LABELS = {
    "exact": ("green", "Exact verification source"),
    "proxy": ("orange", "Advisory comparator (proxy) — not ingestion provenance"),
    "unsupported": ("red", "No external comparator — see DQC scorecard"),
}


@st.cache_resource
def get_connection():
    return duckdb.connect(DB_PATH, read_only=True)


def load_scorecard(path: str) -> dict | None:
    p = Path(path)
    if p.exists():
        return json.loads(p.read_text())
    return None


def load_ads_data():
    try:
        conn = get_connection()
        df = conn.execute(
            f"SELECT calendar_date, day_name, is_business_day, "
            f"order_count, daily_revenue, calculated_at "
            f"FROM {ADS_TABLE} ORDER BY calendar_date"
        ).fetchdf()
        return df
    except Exception:
        return None


def render_link_badge(link_status: str) -> None:
    color, label = LINK_STATUS_LABELS.get(link_status, ("gray", f"Status: {link_status}"))
    st.caption(f":{color}_circle: {label}")


def render_error_badge() -> None:
    st.caption(":gray_circle: Data unavailable — check database connection")


def section_mode_banner():
    if IS_FIXTURE_MODE:
        st.warning("FIXTURE/DEMO MODE — Static seed data, not live ingestion.")
    st.title(f"{MART_NAME} Dashboard")
    st.caption(f"Database: {DB_PATH}")


def section_dqc_scorecard():
    st.header("Data Quality Scorecard")
    scorecard = load_scorecard(DQC_SCORECARD_PATH)
    if not scorecard:
        st.warning("Scorecard not found. Run `dbt test` then `dqc-update`.")
        return

    controls = scorecard.get("controls", [])
    if not controls:
        st.info("No DQC controls recorded. Run the DQC pipeline.")
        return

    cols = st.columns(min(len(controls), 4))
    for i, ctrl in enumerate(controls):
        status = ctrl.get("status", "unknown")
        color = {"pass": "green", "fail": "red", "exhausted": "orange"}.get(status, "gray")
        with cols[i % len(cols)]:
            st.markdown(f":{color}_circle: **{ctrl.get('class', '?')}**")
            st.caption(f"{ctrl.get('metric', '?')}: {status}")
            if status == "exhausted" and "attempts" in ctrl:
                with st.expander("Resource exhaustion evidence"):
                    for a in ctrl["attempts"]:
                        st.text(f"  {a.get('source','?')}: {a.get('result','?')} — {a.get('reason','?')}")


def section_metric_cards(ads_df):
    st.header("Metrics Overview")

    if not CONTRACTED_METRICS:
        st.info("No contracted metrics defined.")
        return

    data_available = ads_df is not None and not ads_df.empty
    cols = st.columns(len(CONTRACTED_METRICS))

    for i, metric in enumerate(CONTRACTED_METRICS):
        with cols[i]:
            label = f"{metric['name']} ({metric['id']})"
            ads_col = metric.get("ads_column", "")
            link_status = metric.get("link_status", "unsupported")

            if data_available and ads_col and ads_col in ads_df.columns:
                value = ads_df[ads_col].sum()
                st.metric(label=label, value=f"{value:,.2f}")
                render_link_badge(link_status)
            else:
                st.metric(label=label, value="—")
                render_error_badge()

    if not data_available:
        st.info("Run `dbt seed && dbt run` to populate metrics from the ADS table.")


def section_trend_chart(ads_df):
    st.header("Revenue Trend")
    if ads_df is not None and not ads_df.empty and "calendar_date" in ads_df.columns:
        revenue_cols = [m["ads_column"] for m in CONTRACTED_METRICS if m.get("ads_column") == "daily_revenue"]
        if revenue_cols and "daily_revenue" in ads_df.columns:
            st.line_chart(ads_df.set_index("calendar_date")["daily_revenue"])
        else:
            st.info("No revenue metric contracted for trend display.")
    else:
        st.info("No trend data available. Run `dbt seed && dbt run` first.")


def section_provenance():
    st.header("Data Provenance")
    st.markdown(
        "| Field | Description |\n"
        "|-------|------------|\n"
        "| `provider` | Data source identifier |\n"
        "| `pull_ts_utc` | When ingestion ran |\n"
        "| `quote_ts_utc` | Source data timestamp |\n"
        "| `run_id` | Pipeline run trace |"
    )


def main():
    st.set_page_config(page_title=f"{MART_NAME} Dashboard", layout="wide")
    section_mode_banner()
    section_dqc_scorecard()
    ads_df = load_ads_data()
    section_metric_cards(ads_df)
    section_trend_chart(ads_df)
    section_provenance()


if __name__ == "__main__":
    main()
