"""
{mart_name} Dashboard — Streamlit Presentation Layer

Generated by mart-forge scaffold from the signed TDD dashboard specification.
Sections: mode banner, DQC scorecard, metric cards, trend chart, provenance.
Connects to DuckDB (local fixture or MotherDuck-compatible URI via env).
"""

import json
import os
from pathlib import Path

import duckdb
import streamlit as st

MART_NAME = "{mart_name}"
DB_PATH = os.getenv("MART_DB_PATH", "{db_name}.duckdb")
DQC_SCORECARD_PATH = os.getenv("DQC_SCORECARD_PATH", "dqc_scorecard.json")
IS_FIXTURE_MODE = os.getenv("MART_FIXTURE_MODE", "true").lower() == "true"

ADS_TABLE = "{prefix}_ads_exec_dashboard"
DWS_TABLE = "{prefix}_dws_daily_revenue_1d"

LINK_STATUS_LABELS = {
    "exact": ("green", "Exact verification source"),
    "proxy": ("orange", "Advisory comparator (proxy) — not ingestion provenance"),
    "unsupported": ("red", "No external comparator — see DQC scorecard"),
}


@st.cache_resource
def get_connection():
    return duckdb.connect(DB_PATH, read_only=True)


def load_scorecard(path: str) -> dict | None:
    p = Path(path)
    if p.exists():
        return json.loads(p.read_text())
    return None


def load_ads_data():
    try:
        conn = get_connection()
        df = conn.execute(
            f"SELECT calendar_date, day_name, is_business_day, "
            f"order_count, daily_revenue, calculated_at "
            f"FROM {ADS_TABLE} ORDER BY calendar_date"
        ).fetchdf()
        return df
    except Exception:
        return None


def load_dws_data():
    try:
        conn = get_connection()
        df = conn.execute(
            f"SELECT date_key, order_count, daily_revenue, calculated_at "
            f"FROM {DWS_TABLE} ORDER BY date_key"
        ).fetchdf()
        return df
    except Exception:
        return None


def render_link_badge(link_status: str) -> None:
    color, label = LINK_STATUS_LABELS.get(link_status, ("gray", f"Status: {link_status}"))
    st.caption(f":{color}_circle: {label}")


def section_mode_banner():
    if IS_FIXTURE_MODE:
        st.warning("FIXTURE/DEMO MODE — Static seed data, not live ingestion.")
    st.title(f"{MART_NAME} Dashboard")
    st.caption(f"Database: {DB_PATH}")


def section_dqc_scorecard():
    st.header("Data Quality Scorecard")
    scorecard = load_scorecard(DQC_SCORECARD_PATH)
    if not scorecard:
        st.warning("Scorecard not found. Run `dbt test` then `dqc-update`.")
        return

    controls = scorecard.get("controls", [])
    if not controls:
        st.info("No DQC controls recorded. Run the DQC pipeline.")
        return

    cols = st.columns(min(len(controls), 4))
    for i, ctrl in enumerate(controls):
        status = ctrl.get("status", "unknown")
        color = {"pass": "green", "fail": "red", "exhausted": "orange"}.get(status, "gray")
        with cols[i % len(cols)]:
            st.markdown(f":{color}_circle: **{ctrl.get('class', '?')}**")
            st.caption(f"{ctrl.get('metric', '?')}: {status}")
            if status == "exhausted" and "attempts" in ctrl:
                with st.expander("Resource exhaustion evidence"):
                    for a in ctrl["attempts"]:
                        st.text(f"  {a.get('source','?')}: {a.get('result','?')} — {a.get('reason','?')}")


def section_metric_cards(ads_df):
    st.header("Metrics Overview")

    if ads_df is not None and not ads_df.empty:
        total_revenue = ads_df["daily_revenue"].sum()
        total_orders = ads_df["order_count"].sum()
        avg_order_value = total_revenue / total_orders if total_orders > 0 else 0

        col1, col2, col3 = st.columns(3)
        with col1:
            st.metric(label="Total Revenue (M-1)", value=f"${total_revenue:,.2f}")
            render_link_badge("exact")
        with col2:
            st.metric(label="Total Orders (M-2)", value=f"{total_orders:,}")
            render_link_badge("exact")
        with col3:
            st.metric(label="Avg Order Value", value=f"${avg_order_value:,.2f}")
            render_link_badge("proxy")
    else:
        col1, col2, col3 = st.columns(3)
        with col1:
            st.metric(label="Total Revenue (M-1)", value="—")
            render_link_badge("unsupported")
        with col2:
            st.metric(label="Total Orders (M-2)", value="—")
            render_link_badge("unsupported")
        with col3:
            st.metric(label="Avg Order Value", value="—")
            render_link_badge("unsupported")
        st.info("Run `dbt seed && dbt run` to populate metrics from the ADS table.")


def section_trend_chart(ads_df):
    st.header("Revenue Trend")
    if ads_df is not None and not ads_df.empty and "calendar_date" in ads_df.columns:
        st.line_chart(ads_df.set_index("calendar_date")["daily_revenue"])
    else:
        st.info("No trend data available. Run `dbt seed && dbt run` first.")


def section_provenance():
    st.header("Data Provenance")
    st.markdown(
        "| Field | Description |\n"
        "|-------|------------|\n"
        "| `provider` | Data source identifier |\n"
        "| `pull_ts_utc` | When ingestion ran |\n"
        "| `quote_ts_utc` | Source data timestamp |\n"
        "| `run_id` | Pipeline run trace |"
    )


def main():
    st.set_page_config(page_title=f"{MART_NAME} Dashboard", layout="wide")
    section_mode_banner()
    section_dqc_scorecard()
    ads_df = load_ads_data()
    section_metric_cards(ads_df)
    section_trend_chart(ads_df)
    section_provenance()


if __name__ == "__main__":
    main()
