"""
Dashboard Template — Streamlit Presentation Layer

Generated by mart-forge scaffold from the signed TDD dashboard specification.
Structure:
1. Mode banner (fixture vs live)
2. DQC scorecard grid — driven by dqc_scorecard.json
3. Metric cards — driven by TDD dashboard spec, each with link_status badge
4. Trend chart placeholder — driven by DWS time-series data
5. Data provenance panel — driven by ODS provenance columns
"""

import json
import os
from pathlib import Path

import streamlit as st

MART_NAME = "{mart_name}"
DQC_SCORECARD_PATH = "dqc_scorecard.json"
IS_FIXTURE_MODE = os.getenv("MART_FIXTURE_MODE", "false").lower() == "true"

LINK_STATUS_LABELS = {
    "exact": ("green", "Exact verification source"),
    "proxy": ("orange", "Advisory comparator (proxy) — not ingestion provenance"),
    "unsupported": ("red", "No external comparator — see DQC scorecard"),
}


def load_scorecard(path: str) -> dict | None:
    p = Path(path)
    if p.exists():
        return json.loads(p.read_text())
    return None


def render_link_badge(link_status: str, url: str | None = None) -> None:
    color, label = LINK_STATUS_LABELS.get(link_status, ("gray", f"Status: {link_status}"))
    if url and link_status in ("exact", "proxy"):
        st.caption(f":{color}_circle: [{label}]({url})")
    else:
        st.caption(f":{color}_circle: {label}")


def section_mode_banner():
    if IS_FIXTURE_MODE:
        st.warning("FIXTURE/DEMO MODE — Static data, not live.")
    st.title(f"{MART_NAME} Dashboard")


def section_dqc_scorecard():
    st.header("Data Quality Scorecard")
    scorecard = load_scorecard(DQC_SCORECARD_PATH)
    if not scorecard:
        st.warning("Scorecard not found. Run `dbt test` then `dqc-update`.")
        return

    controls = scorecard.get("controls", [])
    if not controls:
        st.info("No DQC controls recorded. Run the DQC pipeline.")
        return

    cols = st.columns(min(len(controls), 4))
    for i, ctrl in enumerate(controls):
        status = ctrl.get("status", "unknown")
        color = {"pass": "green", "fail": "red", "exhausted": "orange"}.get(status, "gray")
        with cols[i % len(cols)]:
            st.markdown(f":{color}_circle: **{ctrl.get('class', '?')}**")
            st.caption(f"{ctrl.get('metric', '?')}: {status}")
            if status == "exhausted" and "attempts" in ctrl:
                with st.expander("Resource exhaustion evidence"):
                    for a in ctrl["attempts"]:
                        st.text(f"  {a.get('source','?')}: {a.get('result','?')} — {a.get('reason','?')}")


def section_metric_cards():
    st.header("Metrics Overview")
    st.markdown("*Each metric card traces to a BRD metric entry and TDD column specification.*")

    col1, col2, col3 = st.columns(3)

    with col1:
        st.metric(label="Metric M-1 (from TDD)", value="—")
        render_link_badge("exact")

    with col2:
        st.metric(label="Metric M-2 (from TDD)", value="—")
        render_link_badge("proxy")

    with col3:
        st.metric(label="Metric M-3 (from TDD)", value="—")
        render_link_badge("unsupported")

    st.info(
        "Metric values are populated from the ADS table after scaffold and `dbt run`. "
        "Replace placeholder names with actual BRD metric identifiers."
    )


def section_trend_chart():
    st.header("Trend")
    st.markdown("*Time-series visualization from DWS aggregation tables.*")
    st.line_chart({"date": [], "value": []})
    st.caption("Chart populated after `dbt run` produces DWS time-series data.")


def section_provenance():
    st.header("Data Provenance")
    st.markdown(
        "| Field | Description |\n"
        "|-------|------------|\n"
        "| `provider` | Data source identifier |\n"
        "| `pull_ts_utc` | When ingestion ran |\n"
        "| `quote_ts_utc` | Source data timestamp |\n"
        "| `run_id` | Pipeline run trace |"
    )


def main():
    st.set_page_config(page_title=f"{MART_NAME} Dashboard", layout="wide")
    section_mode_banner()
    section_dqc_scorecard()
    section_metric_cards()
    section_trend_chart()
    section_provenance()


if __name__ == "__main__":
    main()
